In [28]:
# import dependencies
import pandas as pd
import json
#pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

In [4]:
Youtube_Data = pd.read_csv('US_youtube_trending_data.csv')

Youtube_Data.head()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare..."
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628,40221,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11T16:38:55Z,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12T00:00:00Z,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856,7647,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL → http://bit.ly/subscribe-xxl...
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964,2196,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...

In [8]:
Youtube_Data.dtypes

video_id             object
title                object
publishedAt          object
channelId            object
channelTitle         object
categoryId            int64
trending_date        object
tags                 object
view_count            int64
likes                 int64
dislikes              int64
comment_count         int64
thumbnail_link       object
comments_disabled      bool
ratings_disabled       bool
description          object
dtype: object

In [9]:
# Number of Records in data
len(Youtube_Data)

143390

In [11]:
print ("Rows     : " , Youtube_Data.shape[0]) #Displays numbers of rows .
print ("Columns  : " , Youtube_Data.shape[1]) # and column our dataset contains.
print ("\nFeatures : \n", Youtube_Data.columns.tolist())#displays column names
print ("\nMissing values :  ", Youtube_Data.isnull().sum().values.sum())   #find missing values
print ("\nUnique values :  \n", Youtube_Data.nunique())  # Count distinct observations

Rows     :  143390
Columns  :  16

Features :
 ['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle', 'categoryId', 'trending_date', 'tags', 'view_count', 'likes', 'dislikes', 'comment_count', 'thumbnail_link', 'comments_disabled', 'ratings_disabled', 'description']

Missing values :   3663

Unique values :
 video_id              26273
title                 26896
publishedAt           25881
channelId              6065
channelTitle           6175
categoryId               15
trending_date           697
tags                  19117
view_count           139730
likes                 98006
dislikes              13179
comment_count         28951
thumbnail_link        26273
comments_disabled         2
ratings_disabled          2
description           26843
dtype: int64

In [12]:
# finding number of null records for each column
Youtube_Data.isna().sum()

video_id                0
title                   0
publishedAt             0
channelId               0
channelTitle            0
categoryId              0
trending_date           0
tags                    0
view_count              0
likes                   0
dislikes                0
comment_count           0
thumbnail_link          0
comments_disabled       0
ratings_disabled        0
description          3663
dtype: int64

In [15]:
Youtube_Data.head()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare..."
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628,40221,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11T16:38:55Z,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12T00:00:00Z,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856,7647,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL → http://bit.ly/subscribe-xxl...
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964,2196,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...

In [16]:
Youtube_Data.describe()

          categoryId    view_count         likes       dislikes  comment_count
count  143390.000000  1.433900e+05  1.433900e+05  143390.000000   1.433900e+05
mean       18.845317  2.627201e+06  1.402497e+05    2126.222505   1.160808e+04
std         6.779560  6.839864e+06  4.033689e+05   10921.673043   8.283483e+04
min         1.000000  0.000000e+00  0.000000e+00       0.000000   0.000000e+00
25%        17.000000  5.057688e+05  2.034100e+04       0.000000   1.426000e+03
50%        20.000000  1.036178e+06  4.791700e+04     400.000000   3.256000e+03
75%        24.000000  2.338435e+06  1.207062e+05    1379.000000   7.857000e+03
max        29.000000  2.644074e+08  1.602153e+07  879354.000000   6.738537e+06

In [20]:
#changing published date , trending_date to datetime datatype.
Youtube_Data.publishedAt= pd.to_datetime(Youtube_Data.publishedAt)
Youtube_Data.trending_date= pd.to_datetime(Youtube_Data.trending_date)

In [21]:
#Adding column for year to the dataframe
Youtube_Data['Year']=Youtube_Data['publishedAt'].dt.year
Youtube_Data['Month']=Youtube_Data.publishedAt.dt.month

In [22]:
Youtube_Data.head()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description,Year,Month
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11 19:20:14+00:00,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12 00:00:00+00:00,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...,2020,8
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11 17:00:10+00:00,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12 00:00:00+00:00,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare...",2020,8
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11 16:34:06+00:00,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12 00:00:00+00:00,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628,40221,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...,2020,8
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11 16:38:55+00:00,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12 00:00:00+00:00,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856,7647,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL → http://bit.ly/subscribe-xxl...,2020,8
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11 15:10:05+00:00,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12 00:00:00+00:00,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964,2196,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...,2020,8

In [23]:
# gives us various count of video in each channel category
Youtube_Data.groupby("categoryId").size().reset_index(name="video_count") \
    .sort_values("video_count", ascending=False).head(20)

    categoryId  video_count
9           24        28885
6           20        27150
2           10        24140
4           17        15147
7           22        12777
8           23         7927
0            1         5687
10          25         5521
13          28         4507
11          26         4291
12          27         3369
1            2         2536
5           19          694
3           15          645
14          29          114

In [29]:
#Getting category for the category file
#we need id and title from this file which are under items tag and snippet contain title
with open("US_category_id.json") as f:
    categories = json.load(f)["items"]
cat_dict = {}
category=[]
for cat in categories:
    category.append([cat["id"],cat["snippet"]["title"]])

In [30]:
df_category = pd.DataFrame(category,columns=['categoryId','category']) 
df_category.head(20)

   categoryId               category
0           1       Film & Animation
1           2       Autos & Vehicles
2          10                  Music
3          15         Pets & Animals
4          17                 Sports
5          18           Short Movies
6          19        Travel & Events
7          20                 Gaming
8          21          Videoblogging
9          22         People & Blogs
10         23                 Comedy
11         24          Entertainment
12         25        News & Politics
13         26          Howto & Style
14         27              Education
15         28   Science & Technology
16         29  Nonprofits & Activism
17         30                 Movies
18         31        Anime/Animation
19         32       Action/Adventure

In [31]:
df_category.categoryId=df_category.categoryId.astype('int64')
#merge YT Data Frame and df_category to get category names
df_merge = Youtube_Data.merge(df_category, on = 'categoryId', how = 'inner')
df_merge['category']

0                People & Blogs
1                People & Blogs
2                People & Blogs
3                People & Blogs
4                People & Blogs
                  ...
143385    Nonprofits & Activism
143386    Nonprofits & Activism
143387    Nonprofits & Activism
143388    Nonprofits & Activism
143389    Nonprofits & Activism
Name: category, Length: 143390, dtype: object

In [36]:
# Create summary chart for video counts by categories
agg_func_count = {'view_count': ['count', 'nunique', 'size']}
df_merge.groupby(['category']).agg(agg_func_count)

#change to clean data frame name
Youtube_Data_Updated = df_merge

In [37]:
# Youtube Data for 2020
YT_Data_2020 = Youtube_Data_Updated.loc[(Youtube_Data_Updated['Year']) == 2020]

In [50]:
# Counts of video in each category published in 2020
YT_2020_Category_Summary = {'view_count': ['count', 'nunique', 'size']}
YT_Data_2020.groupby(['category']).agg(agg_func_count)

                      view_count
                           count nunique  size
category
Autos & Vehicles             574     573   574
Comedy                      1740    1740  1740
Education                    667     667   667
Entertainment               5549    5539  5549
Film & Animation            1127    1126  1127
Gaming                      2723    2722  2723
Howto & Style               1373    1373  1373
Music                       6446    6438  6446
News & Politics             1092    1092  1092
Nonprofits & Activism         25      25    25
People & Blogs              2384    2383  2384
Pets & Animals               183     183   183
Science & Technology        1346    1346  1346
Sports                      3401    3399  3401
Travel & Events              102     102   102

In [ ]:
# mean, median, mode, and average of the video categories count list (max, min, mode)
# Calculate total likes
# Avaerage of likes against total volume of videos
#